version: 2

defaults: &defaults
  docker:
    - image: circleci/node

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run tests
          command: npm test
  build:
    <<: *defaults
    steps:
      - run: npm run build
  release:
    <<: *defaults
    steps:
      - run:
          name: "Versioning"
          command: |
            standard-version
      - run:
          name: "Pushing tags"
          command: |
            git push --follow-tags origin master
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  version: 2
  test-release:
    jobs:
      - test
      - build:
          requires:
            - test
      - release:
          filters:
            branches:
              only: master
          requires:
            - build
