version: 2

jobs:
  release:

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn
      - run:
          name: Run tests
          command: yarn run test
      - run: yarn run build
      - run:
          name: "Versioning"
          command: |
            standard-version
      - run:
          name: "Pushing tags"
          command: |
            git push --follow-tags origin master
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
            - persist_to_workspace:
                root: ~/mongofn
                paths: .

workflows:
  version: 2
  test-release:
    jobs:
      - release:
          filters:
            branches:
              only: master
